#pragma once

#include"framework.h"

SILVERAROWANACORE_API int GetRawInput(LPARAM lParam);
SILVERAROWANACORE_API BOOL IsKeyPressed(int vKey);
SILVERAROWANACORE_API BOOL SendUnicodeInput(TCHAR c);
SILVERAROWANACORE_API BOOL SendAsciiInput(TCHAR c);
SILVERAROWANACORE_API VOID AutoCode(LPTSTR code);